// export { default as Box } from './Box'
export { default as Box } from './Box'
export { default as Button } from './Button'
export { default as Buttons } from './Buttons'
export { default as Content } from './Content'
export { default as Delete } from './Delete'
export { default as Icon } from './Icon'
export { default as Image } from './Image'
export { default as Notification } from './Notification'
// export { default as other } from './Other'
export { default as Progress } from './Progress'
export { default as Table } from './Table'
export { default as Tag } from './Tag'
export { default as Tags } from './Tags'
export { default as Title } from './Title'
export { default as Subtitle } from './Subtitle'
